std = "sele-conky"

[config]
empty_if = { comments_count = true }
unused_variable = { ignore_pattern = "conky_|result|ok|^_" }
shadowing = { ignore_pattern = "result|ok|^_" }
# feature request for this config: https://github.com/Kampfkarren/selene/issues/181
# global_usage = { ignore_pattern = "^__" }

[rules]
# global_usage = "allow"
# unused_variable = "allow"
# shadowing = "allow"
